# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.11
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ksp_console')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ksp_console')
    _ksp_console = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ksp_console', [dirname(__file__)])
        except ImportError:
            import _ksp_console
            return _ksp_console
        try:
            _mod = imp.load_module('_ksp_console', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ksp_console = swig_import_helper()
    del swig_import_helper
else:
    import _ksp_console
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

KSP_INPUT_YAW = _ksp_console.KSP_INPUT_YAW
KSP_INPUT_ROLL = _ksp_console.KSP_INPUT_ROLL
KSP_INPUT_PITCH = _ksp_console.KSP_INPUT_PITCH
KSP_INPUT_XTRANS = _ksp_console.KSP_INPUT_XTRANS
KSP_INPUT_YTRANS = _ksp_console.KSP_INPUT_YTRANS
KSP_INPUT_ZTRANS = _ksp_console.KSP_INPUT_ZTRANS
KSP_INPUT_THRUST = _ksp_console.KSP_INPUT_THRUST
BUTTON_STAGE = _ksp_console.BUTTON_STAGE
BUTTON_RCS = _ksp_console.BUTTON_RCS
BUTTON_SAS = _ksp_console.BUTTON_SAS
BUTTON_GEAR = _ksp_console.BUTTON_GEAR
BUTTON_SWITCH_RIGHT = _ksp_console.BUTTON_SWITCH_RIGHT
BUTTON_SWITCH_LEFT = _ksp_console.BUTTON_SWITCH_LEFT
BUTTON_LIGHTS = _ksp_console.BUTTON_LIGHTS
BUTTON_BREAKS = _ksp_console.BUTTON_BREAKS
BUTTON_ACTION_1 = _ksp_console.BUTTON_ACTION_1
BUTTON_ACTION_2 = _ksp_console.BUTTON_ACTION_2
BUTTON_ACTION_3 = _ksp_console.BUTTON_ACTION_3
BUTTON_ACTION_4 = _ksp_console.BUTTON_ACTION_4
BUTTON_ACTION_5 = _ksp_console.BUTTON_ACTION_5
BUTTON_ACTION_6 = _ksp_console.BUTTON_ACTION_6
BUTTON_ACTION_7 = _ksp_console.BUTTON_ACTION_7
BUTTON_ACTION_8 = _ksp_console.BUTTON_ACTION_8
BUTTON_ACTION_9 = _ksp_console.BUTTON_ACTION_9
BUTTON_ACTION_10 = _ksp_console.BUTTON_ACTION_10
BUTTON_SOLAR_ON = _ksp_console.BUTTON_SOLAR_ON
BUTTON_SOLAR_OFF = _ksp_console.BUTTON_SOLAR_OFF
BUTTON_ENGINES_OFF = _ksp_console.BUTTON_ENGINES_OFF
BUTTON_ENGINES_ON = _ksp_console.BUTTON_ENGINES_ON
BUTTON_ABORT = _ksp_console.BUTTON_ABORT
BUTTON_FUEL = _ksp_console.BUTTON_FUEL
BUTTON_REACTION_WHEELS = _ksp_console.BUTTON_REACTION_WHEELS
BUTTON_STORE = _ksp_console.BUTTON_STORE
BUTTON_LOAD = _ksp_console.BUTTON_LOAD
BUTTON_CAMERA = _ksp_console.BUTTON_CAMERA
BUTTON_TEST = _ksp_console.BUTTON_TEST
BUTTON_EVA = _ksp_console.BUTTON_EVA
BUTTON_IVA = _ksp_console.BUTTON_IVA
BUTTON_SAS_MODE = _ksp_console.BUTTON_SAS_MODE
BUTTON_SPEED_MODE = _ksp_console.BUTTON_SPEED_MODE
BUTTON_THRUST_FULL = _ksp_console.BUTTON_THRUST_FULL
BUTTON_THRUST_ZERO = _ksp_console.BUTTON_THRUST_ZERO
BUTTON_CHUTES = _ksp_console.BUTTON_CHUTES
INFO_HEIGHT = _ksp_console.INFO_HEIGHT
INFO_SPEED = _ksp_console.INFO_SPEED
INFO_ACTION_GROUPS = _ksp_console.INFO_ACTION_GROUPS
INFO_SURFACE_HEIGHT = _ksp_console.INFO_SURFACE_HEIGHT
INFO_SURFACE_TIME = _ksp_console.INFO_SURFACE_TIME
INFO_APOAPSIS = _ksp_console.INFO_APOAPSIS
INFO_APOAPSIS_TIME = _ksp_console.INFO_APOAPSIS_TIME
INFO_PERIAPSIS = _ksp_console.INFO_PERIAPSIS
INFO_PERIAPSIS_TIME = _ksp_console.INFO_PERIAPSIS_TIME
CMD_GET_UPDATES = _ksp_console.CMD_GET_UPDATES
CMD_UPDATE_CONSOLE = _ksp_console.CMD_UPDATE_CONSOLE
CMD_INIT = _ksp_console.CMD_INIT
# This file is compatible with both classic and new-style classes.


